const menuToggle=document.querySelector('#menuToggle');const mobileMenu=document.querySelector('#mobileMenu');menuToggle.addEventListener('click',()=>{const open=mobileMenu.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open)});const content={seating:['SEATING','Seating','Lear','Seating brings comfort, support and function into the vehicle cabin. Localising this capability brings an essential part of the vehicle closer to Saudi automotive production.'],body:['BODY-IN-WHITE','Body-in-white','Shin Young','The body-in-white forms the structural foundation of a vehicle. Establishing this manufacturing capability locally supports a critical stage of the automotive value chain.'],chassis:['CHASSIS','Chassis','BENTELER','Chassis components provide the foundation for vehicle assembly. Local capability strengthens the connection between specialist component manufacturing and the OEM production line.'],interior:['INTERIOR PLASTICS','Interior plastics','Fangxin','From cabin surfaces to functional interior parts, plastic components shape the in-vehicle experience. Local manufacturing brings this capability into the Saudi supply chain.'],exterior:['EXTERIOR PLASTICS','Exterior plastics','JVIS','Exterior plastic components combine form and function across the vehicle. Localising their manufacture expands the range of components available within the Kingdom\'s automotive ecosystem.']};document.querySelectorAll('[data-cap]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-cap]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-selected','false')});btn.classList.add('active');btn.setAttribute('aria-selected','true');const [label,title,supplier,text]=content[btn.dataset.cap];document.querySelector('#capLabel').textContent=label;document.querySelector('#capTitle').textContent=title;document.querySelector('#capSupplier').textContent=supplier;document.querySelector('#capText').textContent=text}));const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const capImages={seating:'assets/seating-line.jpg',body:'assets/lear-production.jpg',chassis:'assets/equipment.png',interior:'assets/seating-line.jpg',exterior:'assets/equipment.png'};document.querySelectorAll('[data-cap]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('#capImage').src=capImages[btn.dataset.cap]}));
const capabilitySection=document.querySelector('#capabilities');const capabilityButtons=[...document.querySelectorAll('#capabilities [data-cap]')];let scrollTick=false;function syncCapabilityToScroll(){if(!capabilitySection)return;const rect=capabilitySection.getBoundingClientRect();const travel=Math.max(1,capabilitySection.offsetHeight-window.innerHeight);const progress=Math.min(0.999,Math.max(0,-rect.top/travel));const index=Math.min(capabilityButtons.length-1,Math.floor(progress*capabilityButtons.length));const active=capabilityButtons[index];if(active&&!active.classList.contains('active'))active.click();capabilitySection.classList.toggle('is-scrolling',progress>0&&progress<.99);scrollTick=false}window.addEventListener('scroll',()=>{if(!scrollTick){window.requestAnimationFrame(syncCapabilityToScroll);scrollTick=true}},{passive:true});syncCapabilityToScroll();
const footerLinks=document.querySelector('.footer-links');if(footerLinks){footerLinks.insertAdjacentHTML('beforeend','<a href="mailto:info@tasarusupplierhub.sa">info@tasarusupplierhub.sa</a>')}
const networkSection=document.querySelector('.ecosystem');if(networkSection){networkSection.insertAdjacentHTML('afterbegin','<div class="ecosystem-background" aria-hidden="true"></div>');const networkBackground=networkSection.querySelector('.ecosystem-background');const networkImages=['assets/network-global-expertise.png','assets/network-hub.png','assets/network-production.png'];const networkCards=[...networkSection.querySelectorAll('.ecosystem-flow article')];const showNetworkImage=index=>{networkBackground.style.backgroundImage="linear-gradient(120deg,rgba(0,23,48,.88),rgba(0,23,48,.56)),url('"+networkImages[index]+"')";networkBackground.style.opacity='.34'};const hideNetworkImage=()=>{networkBackground.style.opacity='0'};networkCards.forEach((card,index)=>{card.addEventListener('mouseenter',()=>showNetworkImage(index));card.addEventListener('mouseleave',hideNetworkImage);card.addEventListener('focusin',()=>showNetworkImage(index));card.addEventListener('focusout',hideNetworkImage)})}
const locImage=document.querySelector('.location-image');if(locImage&&!locImage.querySelector('.mobility-popup'))locImage.insertAdjacentHTML('beforeend','<button class="map-pin" aria-label="Show MASARAT Mobility Park details">●</button><div class="mobility-popup"><strong>MASARAT Mobility Park</strong><span>King Abdullah Economic City</span><span>Saudi Arabia</span><small>Manufacturing · Innovation · Logistics · Talent</small></div>')
const locationVisual=document.querySelector('.location-image img');if(locationVisual){locationVisual.src='https://images.unsplash.com/photo-1565610222536-ef125c59da2e?auto=format&fit=crop&w=1800&q=85';locationVisual.alt='Modern industrial manufacturing facility representing the supplier ecosystem'}
if(locImage&&!locImage.querySelector('.location-map'))locImage.insertAdjacentHTML('afterbegin','<iframe class="location-map" title="Map showing MASARAT Mobility Park in King Abdullah Economic City" loading="lazy" src="https://www.openstreetmap.org/export/embed.html?bbox=38.98%2C22.32%2C39.24%2C22.53&layer=mapnik&marker=22.4316%2C39.1044"></iframe>')
const ecosystemSection=document.querySelector('.ecosystem');if(ecosystemSection&&!document.querySelector('#performance'))ecosystemSection.insertAdjacentHTML('beforebegin','<section class="performance-section section-pad" id="performance"><div class="section-inner"><div class="performance-intro"><div><p class="eyebrow">THE PLATFORM IN NUMBERS</p><h2>Built for <em>local scale.</em></h2></div><p>Five global Tier-1 suppliers, five critical capabilities and one localisation platform bringing automotive manufacturing closer to Saudi production.</p></div><div class="performance-grid"><article class="metric-card"><span>01 / SUPPLIERS</span><strong>5</strong><h3>Global Tier-1 suppliers</h3><p>Specialist manufacturing partners forming the foundation of the hub.</p></article><article class="metric-card"><span>02 / CAPABILITIES</span><strong>5</strong><h3>Critical capabilities</h3><p>Component categories localised for Saudi automotive production.</p></article><article class="metric-card"><span>03 / PLATFORM</span><strong>1</strong><h3>Localisation platform</h3><p>One connected base for suppliers, OEM demand and industrial growth.</p></article><article class="metric-visual"><img src="https://images.unsplash.com/photo-1565793298595-6a879b1d9492?auto=format&fit=crop&w=1200&q=85" alt="Industrial manufacturing equipment in a modern facility"><span>MASARAT MOBILITY PARK · SAUDI ARABIA</span></article></div></div></section>')
const platformSection=document.querySelector('#about');const platformCards=[...document.querySelectorAll('#about .foundation-grid article')];let platformTick=false;function syncPlatformCards(){if(!platformSection||!platformCards.length)return;const r=platformSection.getBoundingClientRect();const travel=Math.max(1,platformSection.offsetHeight-window.innerHeight);const p=Math.min(1,Math.max(0,-r.top/travel));platformSection.classList.toggle('platform-active',p>0&&p<1);platformCards.forEach((card,i)=>{const start=i*0.22;const local=Math.min(1,Math.max(0,(p-start)/(1-start)));const rise=(1-local)*(i*175);const drift=i===0?0:i*8;card.style.transform='translate3d('+drift+'px,'+rise+'px,0)'}) ;platformTick=false}window.addEventListener('scroll',()=>{if(!platformTick){requestAnimationFrame(syncPlatformCards);platformTick=true}},{passive:true});syncPlatformCards();
const heroVisual=document.querySelector('.hero-image img');if(heroVisual){heroVisual.src='https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=2000&q=85';heroVisual.alt='Automotive manufacturing engineer working on an industrial production line'}
const siteHeader=document.querySelector('.site-header');function syncHeader(){if(siteHeader)siteHeader.classList.toggle('is-scrolled',window.scrollY>24)}window.addEventListener('scroll',syncHeader,{passive:true});syncHeader();
const primaryNav=document.querySelector('.desktop-nav');if(primaryNav){const navItems=[['#about','About TSH'],['#suppliers','Tier-1 Suppliers'],['#location','Location & Infrastructure'],['#capabilities','Media & Insights'],['#contact','Contact']];primaryNav.querySelectorAll('a').forEach((link,i)=>{if(navItems[i]){link.href=navItems[i][0];link.textContent=navItems[i][1]}});if(!primaryNav.querySelector('.nav-search'))primaryNav.insertAdjacentHTML('beforeend','<button class="nav-search" type="button" aria-label="Search">⌕</button>')}
const mobileNav=document.querySelector('.mobile-menu');if(mobileNav){const mobileItems=[['#about','About TSH'],['#suppliers','Tier-1 Suppliers'],['#location','Location & Infrastructure'],['#capabilities','Media & Insights'],['#contact','Contact']];mobileNav.querySelectorAll('a').forEach((link,i)=>{if(mobileItems[i]){link.href=mobileItems[i][0];link.textContent=mobileItems[i][1]}})}
const navSearch=document.querySelector('.nav-search');if(navSearch){navSearch.textContent='↗';navSearch.setAttribute('aria-label','Open platform')}
const navSearchIcon=document.querySelector('.nav-search');if(navSearchIcon){navSearchIcon.innerHTML='<img src="assets/search-normal.svg" alt="">';navSearchIcon.setAttribute('aria-label','Search')}
if(navSearchIcon){navSearchIcon.innerHTML='<img src="assets/search-normal.svg?v=2" alt="">';}
const heroImage=document.querySelector('.hero-image');if(heroImage){heroImage.innerHTML='<video class="hero-video" autoplay muted loop playsinline preload="metadata" aria-label="Fangxin automotive manufacturing video"><source src="assets/fangxin-banner.mp4" type="video/mp4"></video>'}
const seatingImage=document.querySelector('#capImage');if(seatingImage){seatingImage.src='assets/seating-line.jpg';document.querySelectorAll('[data-cap="seating"]').forEach(btn=>btn.addEventListener('click',()=>{seatingImage.src='assets/seating-line.jpg'}))}
const performanceImage=document.querySelector('#performance .metric-visual img');if(performanceImage){performanceImage.src='assets/lear-production.jpg';performanceImage.alt='Lear technicians assembling automotive seats'}
document.querySelectorAll('.button span,.text-link span').forEach(arrow=>{arrow.innerHTML='<img src="assets/arrow-right.svg" alt="">';arrow.classList.add('cta-arrow')});
const smoothCapabilityImage=document.querySelector('#capImage');if(smoothCapabilityImage){document.querySelectorAll('#capabilities [data-cap]').forEach(btn=>btn.addEventListener('click',()=>{smoothCapabilityImage.style.opacity='.18';const reveal=()=>{smoothCapabilityImage.style.opacity='1';smoothCapabilityImage.removeEventListener('load',reveal)};smoothCapabilityImage.addEventListener('load',reveal);setTimeout(()=>smoothCapabilityImage.style.opacity='1',500)}))}
const locationMapFrame=document.querySelector('.location-map');if(locationMapFrame){const locationMapImage=document.createElement('img');locationMapImage.className='location-map-image';locationMapImage.alt='Map showing MASARAT Mobility Park in King Abdullah Economic City';locationMapImage.src='https://staticmap.openstreetmap.de/staticmap.php?center=22.4316,39.1044&zoom=11&size=900x600&maptype=mapnik&markers=22.4316,39.1044,red-pushpin';locationMapFrame.replaceWith(locationMapImage)}
const locationMapBase=document.querySelector('.location-image .location-map-image');if(locationMapBase&&!document.querySelector('.location-map-hover-image')){locationMapBase.src='assets/location-map-base.png';locationMapBase.alt='Aerial map of King Abdullah Economic City and the surrounding supplier ecosystem';const locationMapHover=document.createElement('img');locationMapHover.className='location-map-hover-image';locationMapHover.src='assets/location-map-hover.png';locationMapHover.alt='Annotated aerial map showing King Abdullah Economic City, King Salman Automotive Cluster and MASARAT Mobility Park';locationMapBase.after(locationMapHover)}
const capSupplierElement=document.querySelector('#capSupplier');if(capSupplierElement){const jvisLogo='assets/jvis-logo.png';document.querySelectorAll('#capabilities [data-cap]').forEach(btn=>btn.addEventListener('click',()=>{const isJvis=btn.dataset.cap==='exterior';capSupplierElement.classList.toggle('has-logo',isJvis);if(isJvis){capSupplierElement.innerHTML='<img src="'+jvisLogo+'" alt="JVIS">'}else{capSupplierElement.textContent=content[btn.dataset.cap][2]}}))}
const renderCapabilitySupplier=key=>{if(!capSupplierElement)return;const supplier=content[key][2];const logo=key==='seating'?'assets/lear-logo-transparent.png':key==='body'?'assets/young-shin-logo-transparent.png':key==='chassis'?'assets/benteler-logo-transparent.png':key==='interior'?'assets/fangxin-logo-transparent.png':key==='exterior'?'assets/jvis-logo-transparent.png':'';capSupplierElement.classList.toggle('has-logo',Boolean(logo));capSupplierElement.classList.toggle('has-lear-logo',key==='seating');capSupplierElement.classList.toggle('has-shin-logo',key==='body');capSupplierElement.classList.toggle('has-benteler-logo',key==='chassis');capSupplierElement.classList.toggle('has-fangxin-logo',key==='interior');capSupplierElement.classList.toggle('has-jvis-logo',key==='exterior');capSupplierElement.setAttribute('aria-label',supplier);capSupplierElement.innerHTML=logo?'<img src="'+logo+'" alt="'+supplier+'">':supplier};if(capSupplierElement){renderCapabilitySupplier('seating');document.querySelectorAll('#capabilities [data-cap]').forEach(btn=>btn.addEventListener('click',()=>renderCapabilitySupplier(btn.dataset.cap)))}

const searchItems=[
  ['#about','About TSH','Platform role, land, real estate and equipment.'],
  ['#suppliers','Tier-1 Suppliers','Lear, Shin Young, BENTELER, Fangxin and JVIS.'],
  ['#capabilities','Manufacturing Capabilities','Seating, body-in-white, chassis, interior plastics and exterior plastics.'],
  ['#location','Location & Infrastructure','KAEC, King Salman Automotive Cluster, MASARAT Mobility Park and TSH.'],
  ['#contact','Contact','General information about the platform and supplier ecosystem.']
];
if(navSearchIcon&&!document.querySelector('.site-search')){
  document.body.insertAdjacentHTML('beforeend','<div class="site-search" hidden><div class="site-search-panel"><button type="button" class="site-search-close" aria-label="Close search">Close</button><p class="eyebrow">WEBSITE SEARCH</p><h2>Find what you need.</h2><input id="siteSearchInput" type="search" placeholder="Try suppliers, location, chassis..." aria-label="Search TASARU Supplier Hub"><ul id="siteSearchResults"></ul></div></div>');
  const search=document.querySelector('.site-search');
  const input=document.querySelector('#siteSearchInput');
  const results=document.querySelector('#siteSearchResults');
  const render=q=>{const value=(q||'').toLowerCase();const matches=searchItems.filter(item=>(item[1]+' '+item[2]).toLowerCase().includes(value));results.innerHTML=(matches.length?matches:searchItems).map(item=>'<li><a href="'+item[0]+'"><b>'+item[1]+'</b><span>'+item[2]+'</span></a></li>').join('')};
  navSearchIcon.addEventListener('click',()=>{search.hidden=false;render('');input.focus()});
  input.addEventListener('input',()=>render(input.value));
  document.querySelector('.site-search-close').addEventListener('click',()=>search.hidden=true);
  search.addEventListener('click',e=>{if(e.target===search)search.hidden=true});
  search.addEventListener('click',e=>{if(e.target.closest('a'))search.hidden=true});
}
